name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli-electron:
        description: Command to execute Cypress tests for Electron
        default: node runner-electron.js
      cli-chrome:
        description: Command to execute Cypress tests for Chrome
        default: node runner-chrome.js
      cli-edge:
        description: Command to execute Cypress tests for Edge
        default: node runner-edge.js

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Clonar o código
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Passo 2: Instalar dependências
      - name: Install dependencies
        run: yarn install

      # Passo 3: Executar testes no Electron
      - name: Run Cypress Tests for Electron
        env:
          TARGET_TOKEN_ELECTRON: ${{ secrets.TARGET_TOKEN_ELECTRON }} # Token do Tesults
        run: echo "Running: ${{ github.event.inputs.cli-electron }}" && ${{ github.event.inputs.cli-electron }}

  cypress-chrome-tests:
    runs-on: ubuntu-latest
    needs: cypress-electron-tests # Dependência: executar após Electron
    steps:
      # Passo 1: Clonar o código
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Passo 2: Instalar dependências
      - name: Install dependencies
        run: yarn install

      # Passo 3: Executar testes no Chrome
      - name: Run Cypress Tests for Chrome
        env:
          TARGET_TOKEN_CHROME: ${{ secrets.TARGET_TOKEN_CHROME }} # Token do Tesults
        run: echo "Running: ${{ github.event.inputs.cli-chrome }}" && ${{ github.event.inputs.cli-chrome }}

  cypress-edge-tests:
    runs-on: ubuntu-latest
    needs: cypress-chrome-tests # Dependência: executar após Chrome
    steps:
      # Passo 1: Clonar o código
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Passo 2: Instalar dependências
      - name: Install dependencies
        run: yarn install

      # Passo 3: Executar testes no Edge
      - name: Run Cypress Tests for Edge
        env:
          TARGET_TOKEN_EDGE: ${{ secrets.TARGET_TOKEN_EDGE }} # Token do Tesults
        run: echo "Running: ${{ github.event.inputs.cli-edge }}" && ${{ github.event.inputs.cli-edge }}
