name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Specify the Cypress spec to run
        default: "cypress/e2e/*"

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-22.04  # Usando uma versão estável do Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libnss3 libatk1.0-0 libatk-bridge2.0-0 libx11-xcb1 libxcomposite1 libxrandr2 libgbm-dev libasound2

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1920x1080x24 & export DISPLAY=:99

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}  # Garantir que o segredo esteja sendo passado
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
