name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Specify the Cypress spec to run
        default: "cypress/e2e/*"

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-22.04  # Primeiro job, não depende de nenhum outro
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libnss3 libatk1.0-0 libatk-bridge2.0-0 libx11-xcb1 libxcomposite1 libxrandr2 libgbm-dev libasound2

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1920x1080x24 & export DISPLAY=:99

      - name: Cypress run - Electron
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cypress-e2e-chrome:
    runs-on: ubuntu-22.04
    needs: cypress-e2e-electron  # Este job só roda se o Electron passar
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libnss3 libatk1.0-0 libatk-bridge2.0-0 libx11-xcb1 libxcomposite1 libxrandr2 libgbm-dev libasound2

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1920x1080x24 & export DISPLAY=:99

      - name: Cypress run - Chrome
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: chrome
          record: true
          group: UI Chrome
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cypress-e2e-firefox:
    runs-on: ubuntu-22.04
    needs: cypress-e2e-chrome  # Este job só roda se o Chrome passar
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libnss3 libatk1.0-0 libatk-bridge2.0-0 libx11-xcb1 libxcomposite1 libxrandr2 libgbm-dev libasound2

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1920x1080x24 & export DISPLAY=:99

      - name: Cypress run - Firefox
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: firefox
          record: true
          group: UI Firefox
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
