name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli-electron:
        description: Command to execute Cypress tests for Electron
        default: node runner-electron.js
      cli-chrome:
        description: Command to execute Cypress tests for Chrome
        default: node runner-chrome.js
      cli-edge:
        description: Command to execute Cypress tests for Edge
        default: node runner-edge.js

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Clone the code
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Step 2: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 3: Execute Cypress tests on Electron
      - name: Run Cypress Tests for Electron
        env:
          TARGET_TOKEN_ELECTRON: ${{ secrets.TARGET_TOKEN_ELECTRON }} # Tesults token
        run: |
          echo "Running: ${{ github.event.inputs.cli-electron }}"
          ${{ github.event.inputs.cli-electron }}

  cypress-chrome-tests:
    runs-on: ubuntu-latest
    needs: cypress-electron-tests # Dependency: Run after Electron tests
    steps:
      # Step 1: Clone the code
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Step 2: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 3: Execute Cypress tests on Chrome
      - name: Run Cypress Tests for Chrome
        env:
          TARGET_TOKEN_CHROME: ${{ secrets.TARGET_TOKEN_CHROME }} # Tesults token
        run: |
          echo "Running: ${{ github.event.inputs.cli-chrome }}"
          ${{ github.event.inputs.cli-chrome }}

  cypress-edge-tests:
    runs-on: ubuntu-latest
    needs: cypress-chrome-tests # Dependency: Run after Chrome tests
    steps:
      # Step 1: Clone the code
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Step 2: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 3: Execute Cypress tests on Edge
      - name: Run Cypress Tests for Edge
        env:
          TARGET_TOKEN_EDGE: ${{ secrets.TARGET_TOKEN_EDGE }} # Tesults token
        run: |
          echo "Running: ${{ github.event.inputs.cli-edge }}"
          ${{ github.event.inputs.cli-edge }}
