name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Select the runner script to execute
        required: true
        type: choice
        options:
          - "node runner-electron.js"
          - "node runner-chrome.js"
          - "node runner-edge.js"
        default: "node runner-electron.js"

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Clonar o código
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Passo 2: Instalar dependências
      - name: Install dependencies
        run: yarn install

      # Passo 3: Executar testes com o script selecionado
      - name: Run Selected Cypress Tests
        env:
          TESULTS_TOKEN: ${{ secrets.TESULTS_TOKEN }} # Variável de autenticação
        run: echo "Running: ${{ github.event.inputs.cli }}" && ${{ github.event.inputs.cli }}
